#!/bin/bash

fileName="system/fvSchemes"

echo "/*--------------------------------*- C++ -*------------------------*\\"  > "$fileName"
echo "|  F ield         | OpenFOAM: The Open Source CFD Toolbox           |"  >> "$fileName"
echo "|  O peration     | Version:  4.x                                   |"  >> "$fileName"
echo "|  A nd           | Web:      www.OpenFOAM.org                      |"  >> "$fileName"
echo "|  M anipulation  |                                                 |"  >> "$fileName"
echo "\\*-----------------------------------------------------------------*/" >> "$fileName"

echo "FoamFile"                         	>> "$fileName"
echo "{"                                	>> "$fileName"
echo "    version     2.0;"             	>> "$fileName"
echo "    format      ascii;"           	>> "$fileName"
echo "    class       dictionary;"      	>> "$fileName"
echo "    object      fvSchemes;" 			>> "$fileName"
echo "}"                                	>> "$fileName"

echo "" >> "$fileName"

echo "ddtSchemes" 											>> "$fileName"
echo "{" 													>> "$fileName"
echo "    default steadyState;" 							>> "$fileName"
echo "}" 													>> "$fileName"
echo "gradSchemes" 											>> "$fileName"
echo "{" 													>> "$fileName"
echo "    default Gauss linear;" 							>> "$fileName"
echo "    grad(U) cellLimited Gauss linear 1;" 				>> "$fileName"
echo "}" 													>> "$fileName"
echo "divSchemes" 											>> "$fileName"
echo "{" 													>> "$fileName"
echo "    default none;" 									>> "$fileName"
echo "    div(phi,U) bounded Gauss linearUpwindV grad(U);" 	>> "$fileName"
echo "    div(phi,k) bounded Gauss upwind;" 				>> "$fileName"
echo "    div(phi,omega) bounded Gauss upwind;" 			>> "$fileName"
echo "    div((nuEff*dev2(T(grad(U))))) Gauss linear;" 		>> "$fileName"
echo "}" 													>> "$fileName"
echo "laplacianSchemes" 									>> "$fileName"
echo "{" 													>> "$fileName"
echo "    default Gauss linear corrected;" 					>> "$fileName"
echo "}" 													>> "$fileName"
echo "interpolationSchemes" 								>> "$fileName"
echo "{" 													>> "$fileName"
echo "    default linear;" 									>> "$fileName"
echo "}" 													>> "$fileName"
echo "snGradSchemes" 										>> "$fileName"
echo "{" 													>> "$fileName"
echo "    default corrected;" 								>> "$fileName"
echo "}" 													>> "$fileName"
echo "wallDist" 											>> "$fileName"
echo "{" 													>> "$fileName"
echo "    method meshWave;" 								>> "$fileName"
echo "}" 													>> "$fileName"
