#!/bin/bash

fileName="system/fvSolution"

tol_P=1e-7
tol_U=1e-8
tol_k=1e-8
tol_omega=1e-8

echo "/*--------------------------------*- C++ -*------------------------*\\"  > "$fileName"
echo "|  F ield         | OpenFOAM: The Open Source CFD Toolbox           |"  >> "$fileName"
echo "|  O peration     | Version:  4.x                                   |"  >> "$fileName"
echo "|  A nd           | Web:      www.OpenFOAM.org                      |"  >> "$fileName"
echo "|  M anipulation  |                                                 |"  >> "$fileName"
echo "\\*-----------------------------------------------------------------*/" >> "$fileName"

echo "FoamFile"                         	>> "$fileName"
echo "{"                                	>> "$fileName"
echo "    version     2.0;"             	>> "$fileName"
echo "    format      ascii;"           	>> "$fileName"
echo "    class       dictionary;"      	>> "$fileName"
echo "    object      fvSolution;" 			>> "$fileName"
echo "}"                                	>> "$fileName"

echo "" >> "$fileName"

echo "solvers" 							>> "$fileName"
echo "{" 								>> "$fileName"
echo "    p" 							>> "$fileName"
echo "    {" 							>> "$fileName"
echo "        solver GAMG;" 			>> "$fileName"
echo "        tolerance $tol_P;" 		>> "$fileName"
echo "        relTol 0.01;" 			>> "$fileName"
echo "        smoother GaussSeidel;" 	>> "$fileName"
echo "    }" 							>> "$fileName"
echo "    Phi" 							>> "$fileName"
echo "    {" 							>> "$fileName"
echo "        \$p;" 					>> "$fileName"
echo "    }" 							>> "$fileName"
echo "    U" 							>> "$fileName"
echo "    {" 							>> "$fileName"
echo "        solver smoothSolver;" 	>> "$fileName"
echo "        smoother GaussSeidel;" 	>> "$fileName"
echo "        tolerance $tol_U;" 		>> "$fileName"
echo "        relTol 0.1;" 				>> "$fileName"
echo "        nSweeps 1;" 				>> "$fileName"
echo "    }" 							>> "$fileName"
echo "    k" 							>> "$fileName"
echo "    {" 							>> "$fileName"
echo "        solver smoothSolver;" 	>> "$fileName"
echo "        smoother GaussSeidel;" 	>> "$fileName"
echo "        tolerance $tol_k;" 		>> "$fileName"
echo "        relTol 0.1;" 				>> "$fileName"
echo "        nSweeps 1;" 				>> "$fileName"
echo "    }" 							>> "$fileName"
echo "    omega" 						>> "$fileName"
echo "    {" 							>> "$fileName"
echo "        solver smoothSolver;" 	>> "$fileName"
echo "        smoother GaussSeidel;" 	>> "$fileName"
echo "        tolerance $tol_omega;" 	>> "$fileName"
echo "        relTol 0.1;" 				>> "$fileName"
echo "        nSweeps 1;" 				>> "$fileName"
echo "    }" 							>> "$fileName"
echo "}" 								>> "$fileName"
echo "SIMPLE" 							>> "$fileName"
echo "{" 								>> "$fileName"
echo "    nNonOrthagonalCorrectors 0;" 	>> "$fileName"
echo "    consistent yes;" 				>> "$fileName"
echo "    residualControl" 				>> "$fileName"
echo "    {" 							>> "$fileName"
echo "        p 1e-3;" 					>> "$fileName"
echo "        U 1e-4;" 					>> "$fileName"
echo "        \"(k|omega)\" 1e-3; " 	>> "$fileName"
echo "    }" 							>> "$fileName"
echo "}"					 			>> "$fileName"
echo "potentialFlow"					>> "$fileName"
echo "{"					 			>> "$fileName"
echo "    nNonOrthagonalCorrectors 10;"	>> "$fileName"
echo "}"					 			>> "$fileName"
echo "relaxationFactors" 				>> "$fileName"
echo "{"					 			>> "$fileName"
echo "    equations"					>> "$fileName"
echo "    {"					 		>> "$fileName"
echo "        U 0.9;"					>> "$fileName"
echo "        k 0.7;"					>> "$fileName"
echo "        omega 0.7;"				>> "$fileName"
echo "    }"							>> "$fileName"
echo "}"								>> "$fileName"
echo "cache"							>> "$fileName"
echo "{"								>> "$fileName"
echo "    grad(U);"						>> "$fileName"
echo "}"								>> "$fileName"
